/**
 * Beruang API
 * Beruang API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetHistory } from './budgetHistory';
import { Budget } from './budget';


export interface BudgetResponse { 
    budget?: Budget;
    budgetHistories?: Array<BudgetHistory>;
}

